### PR TITLE
Throw error in case of step value is NaN

### LINKED ISSUE #226: convertSteps function miss cases of a string as a divider
I ran into a case where I passed an `undefined` value as part of my expression as `*/undefined * * * *` and `cron.validate()` return `true` and find that it behave the same as a normal `* * * * *`

If I understand correctly, in this case the [`convertSteps`](https://github.com/node-cron/node-cron/blob/2a3970390b8dffa20b0a1bbf5ba2f71e8b4405d2/src/convert-expression/step-values-conversion.js#L4) function should receive `1,2,3,4,5,...,59/undefined` which is not getting picked up by the `^(.+)\/(\d+)$` regex.

https://github.com/node-cron/node-cron/blob/2a3970390b8dffa20b0a1bbf5ba2f71e8b4405d2/src/convert-expression/step-values-conversion.js#L4-L13

Later it gets to the [`normalizeIntegers`](https://github.com/node-cron/node-cron/blob/2a3970390b8dffa20b0a1bbf5ba2f71e8b4405d2/src/convert-expression/index.js#L23) function and: `parseInt('59/undefined')` => `59`

**Proposed Solution:**
We can change the regex to `^(.+)\/(\w+)$` and check as early as possible if `isNaN(divider)` and throw an error in other cases.

### PR DESCRIPTION
**Pull request by ZimGil**
This should resolve #226

### CODE REVIEW

**Comment by ZimGil** [comment]
Oh yeah, I will add a test case for this...

**Comment by ZimGil** [comment]
@niftylettuce - care to review? :)

**Comment by ZimGil** [comment]
@node-cron Care to review?

**Comment by merencia** [comment]
@ZimGil thanks for you PR and sorry about the delay.

**Pull request merged**
