### PR TITLE
Fix features - dependencies - timezone - variable scope

### PR DESCRIPTION
**Pull request by flopal**
Hi,

I use **node v14.5.0** and **npm 6.14.8**, if I can help to debug.

This PR updates a lot of things.

1) **dependencies**. I used _**npm-check**_ library to upgrade all dependencies and to fix some audit issues. see commit 
6f2617b.

2) **timezone**. When I was running the _**npm test**_ command, some tests failed about the timezone. I fixed it by replacing _**tz-offset**_ to _**moment-timezone**_ and updating some files (see the list item in commit 72a454a and change in commit 4f26623).

3) **variable scope**. I replaced all _**var**_ to _**let**_ or _**const**_ (depend on the variable update). See commit 27e1140.

4) **readme**. As I said on 1), I changed the timezone library, so I updated the link / Text in the readme. See commits b487616 and 13f9022 (bad copy-paste in the first commit)

I ran again the _**npm test**_ to check if everything is alright: all tests are passed, but the first test can be failed (or be passed) during the first iteration (depend on delay to reach the result [_**deamon.js**_]).

### CODE REVIEW

**Comment by abdurrahmanekr** [comment]
Hey hi 👋, this repo is insufficient on timezone. If this PR solves this problem, is there any reason not to merge it?

**Comment by flopal** [comment]
Hi ! 👋 

Thank you for your interest to my PR (and this project of course) 🙏 

I guess this project is not maintained or it takes time to find another maintainer. Check this issue #255 

Moreover, my PR could be better - replace **moment-timezone** to another package (refer to [this status](https://momentjs.com/docs/#/-project-status/) on the momentjs website).
- I worked with Luxon and it's pretty like momentjs - it's a tank ! 
- Tz-data could be a better alternative. 💪

I'm waiting for news about this project to know if this project continues or not. I will update my PR if it continues, do nothing (leaves my PR like that) otherwise.

**Comment by merencia** [comment]
Hi there! 

I'm really sorry for the delay.

@flopal thanks for you PR.

**Comment by flopal** [comment]
Don't worry about that @merencia, I understand!

I'm glad to see you back to add a new version on this repo.

**Pull request merged**
