### PR TITLE
fixes #358: creates single instance of date formatter

### LINKED ISSUE #358: Excessive CPU/RAM usage
Hello, here is my problem.

I am new to using node-cron, I scheduled the task correctly and checked that it works correctly. The problem is in the excessive use of CPU/RAM that node-cron generates and it collapses the VPS server where it is stored.

Attached image

image

Although the CPU usage looks low, it increases over time.

All this when the script is started and kept active with pm2

If anyone knows anything about this or how to mediate excessive resource usage, I would be grateful.

### PR DESCRIPTION
**Pull request by gokulchandra**
Potential fix for: https://github.com/node-cron/node-cron/issues/358

The current implementation creates multiple instances of the `Intl.DateTimeFormat` causing excessive memory usage. 

I've tested the current implementation and can confirm that RAM usage has now stabilized.

Related issues:
- https://bugs.chromium.org/p/v8/issues/detail?id=6528
- https://github.com/nodejs/node/issues/31914

### CODE REVIEW

**Comment by gokulchandra** [comment]
Can confirm that this is keeping the memory usage stable after running it for 8 hours. 
Screenshot from 2022-07-23 09-27-11

**Comment by ruettenm** [comment]
what about this PR? It would be great if you could fix the memory leak ;-)

**Comment by gokulchandra** [comment]
> what about this PR? It would be great if you could fix the memory leak ;-)

Waiting for it to be reviewed and merged.

**Comment by adam-nielsen** [comment]
I just tried this patch by using:

    npm remove node-cron
    npm install 'https://github.com/gokulchandra/node-cron/tree/fixes-memory-leak'

And it seems to have fixed the problem:

ecs-memory-usage-node_cron

**Comment by gokulchandra** [comment]
Hey @merencia @flopal @negezor , could you take a look at this PR? It fixes #358

**Review by negezor — APPROVED** [review]

**Comment by jarib** [comment]
Switching to @gokulchandra's fork solved the problem for me too.

image

Any chance of a merge + release @merencia ?

**Comment by GustavoRoss** [comment]
Hey @merencia @flopal @negezor , could you take a look at this PR? It fixes https://github.com/node-cron/node-cron/issues/358

**Comment by negezor** [comment]
@GustavoRoss I don't have rights to merge 😅

**Comment by MaxSassen** [comment]
Fix seems nice :P but what's holding this PR back?

**Comment by guillaumefielddata** [comment]
PR was opened in July 2022.... Switching to croner I guess...

**Comment by EcomGraduates** [comment]
how are we still waiting for this merge?

**Pull request merged**
